### ISSUE TITLE
[Linux] Unexpected message appears

### ISSUE THREAD

**Issue by wangxin921012** [Azure/Azure-Data-Service-Notebook#40]
**Describe the bug**
Unexpected message appears and appears many times.

**To Reproduce**
1. Run command "%adl listaccounts".
2. Set parameter to "adl_accountsadl_acc  = %adl listaccounts --page_index 0 --page_account_number 10"
3. Observer the displayed results

**Expected behavior**
Just list the correct accounts and no unexpected message appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/40196669/41639486-86570a60-7490-11e8-978b-63e13d1e4599.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04 LTS]
 - Browser [Firefox]
 - Jupyter Version [5.5.0]

**Additional context**
This issue just repro on Linux, not repro on Windows.

**Comment by wangxin921012** [comment]
Other issue as this:
![image](https://user-images.githubusercontent.com/40196669/41639759-c239f190-7491-11e8-98b8-c1101c889591.png)
![image](https://user-images.githubusercontent.com/40196669/41639771-d0cac3ce-7491-11e8-813c-dafc056a6043.png)
![image](https://user-images.githubusercontent.com/40196669/41639795-e8b72a40-7491-11e8-9057-c209efb74f08.png)
![image](https://user-images.githubusercontent.com/40196669/41639807-f36c871e-7491-11e8-8b2b-a35a8709a4e4.png)
![image](https://user-images.githubusercontent.com/40196669/41639821-00642d82-7492-11e8-8e33-98c1a81e8977.png)

**Comment by gaoyangxiaozhu** [comment]
@wangxin921012  this is a bug caused by the runtime library `msrest` with **version 0.5.0** which is used for AutoRest generated Python clients and has been referenced by adla/adls python sdk.   for details,  see [#109](https://github.com/Azure/msrest-for-python/issues/109) and [#110](https://github.com/Azure/msrest-for-python/pull/110) and [commit fb63fdbe](https://github.com/Azure/msrest-for-python/commit/fb63fdbebd32c78d899b35da8917c067471eefdf)

You can solve this problem by upgrading `msrest` to the latest version using command (recommend):

```pip install -U msrest```

or degenerate `msrest` to 0.4.29 by using command 

```pip install msrest==0.4.29```

**Comment by wangxin921012** [comment]
Hi @gaoyangxiaozhu , I have upgraded `msrest` to 0.5.1 and restarted jupyter notebook, but this issue still repro, please re-check this issue again and fix it. Thanks.
